language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build && cd build && cp index.html 200.html
deploy:
  provider: surge
  skip_cleanup: true
  domain: ipr.surge.sh
  project: ./build/
on:
  branch: master
